# globals
add_newline = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[â¯](bold green)" #

# package module shows package version number
[package]
disabled = false

[aws]
disabled = true
